# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{attribute_normalizer}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Deering"]
  s.date = %q{2010-01-02}
  s.email = %q{mdeering@mdeering.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "install.rb",
     "install.txt",
     "lib/attribute_normalizer.rb",
     "rails/init.rb",
     "spec/attribute_normalizer_spec.rb",
     "spec/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/mdeering/attribute_normalizer}
  s.post_install_message = %q{
      =============================
      Attribute Normalizer News:

      I am looking for feedback on the roadmap for this gem.  Please visit
      http://github.com/mdeering/attribute_normalizer/blob/master/ROADMAP.textile
      and send your comments, suggestions, and pull requests.

      Cheers,
      Michael Deering http://mdeering.com
      =============================      
    }
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Active Record attribute normalizer that excepts code blocks.}
  s.test_files = [
    "spec/attribute_normalizer_spec.rb",
     "spec/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

